Updated to use new method of spawning multiple sagas
colinbate/redux-form-submit-saga pull request #14
Opened 2017-07-06 23:31 UTC by porksmash

Fixes the redux-saga depreciation warning mentioned in #11

2017-08-01 22:47 UTC, hugobessa requested changes
@porksmash, I think your fork is not compatible with older versions of redux-saga. You are supposing the "all" effect is available, but in old versions like 0.12.x it is not

2017-08-01 22:58 UTC, porksmash commented
That's true, I overlooked that. Do you want to update the peer dependency for redux-saga? It looks like `all` was added in 15.0, which blocks out a lot of versions currently supported by redux-form-submit-saga.

2017-08-02 01:44 UTC, hugobessa commented
I've made a fork of your fork. In there I checked if `all`effect is undefined before using it. And in the case it is not I use the old notation. I also updated the package.json to support redux-saga 0.15.x as well. 

I've sent a PR to your fork so you can update this PR.

2017-08-02 04:01 UTC, porksmash commented
Thanks!

2017-08-02 13:20 UTC, hugobessa approved these changes

2017-08-02 17:34 UTC, hugobessa commented
@colinbate can you merge this?

2017-08-17 16:45 UTC, colinbate commented on src/create.js
> +        yield all([
I haven't tried this, but looking at it, it looks like this would fail since this is the branch where `all` is *not* defined.

2017-08-17 16:46 UTC, colinbate commented on src/form-submit-saga.js
> +      response = yield all([
Same issue as above. At this point `all` is falsy.

2017-08-17 16:55 UTC, colinbate commented
I'll merge this once my comments above are addressed. Sorry for my absence over the past couple months.

2017-08-17 17:30 UTC, hugobessa commented
@colinbate, I guess it's fixed now!

2017-08-17 17:33 UTC, colinbate commented
Thanks, I'll look to merging it now.

2017-08-17 17:35 UTC, merged

2017-08-17 17:35 UTC, porksmash commented
Thanks @hugobessa for taking it all the way

2017-08-17 17:43 UTC, colinbate commented
Published at 1.2.1

Let me know if you have any issues with it.